#!/bin/bash

echo ======================================================================
echo "                Script para borrar kernels viejos"
echo ======================================================================
echo -n "GNU/Linux versión "
lsb_release -d -s
echo
echo -n "Kernel Actual NO BORRARLO:   "
uname -r
echo
echo Kernels Viejos. Dejar al menos uno sin borrar:
dpkg -l | tail -n +6 | grep -E 'linux-image-[0-9]+' | grep -Fv $(uname -r)

if [[ -z "$1" ]]; then
echo

else
echo
echo ===== !!! CUIDADO Va a borrar el kernel $1 !!! =====
echo
read -p "ENTER o Ctr-C para cancelar"

echo ====================
echo Borrando Google Cloud Platform headers $1...
sudo dpkg --purge linux-gcp-headers-$1

echo ====================
echo Borrando headers de Linux... $1
sudo dpkg --purge linux-headers-$1-gcp

echo ====================
echo Borrando imagen $1...
sudo dpkg --purge linux-image-$1-gcp

echo ====================
echo Borrando módulos... $1
sudo dpkg --purge linux-modules-$1-gcp

echo
dpkg -l | tail -n +6 | grep -E 'linux-image-[0-9]+' | grep -Fv $(uname -r)
fi
echo ===== Kernels Instalados: =====
dpkg -l | tail -n +6 | grep -E 'linux-image-[0-9]+'

echo
# Muestra el espacio disponible en disco (linea 1 y 2)
df -H|sed -n '1p;2p'

echo
